2025-09-23 10:56:45,538 - INFO - 2025-09-23 10:56:45 --- Start processing config file: HL13_01.ini ---
2025-09-23 10:56:45,547 - INFO - 2025-09-23 10:56:45 CSV output for this config will be: C:\Users\hsi67063\Box\00-home-pigo.hsiao\TEMP\XML\BJ1_CVD_EtchingRate_Dry3_2025_09_23T10.56.45.csv
2025-09-23 10:56:45,550 - INFO - 2025-09-23 10:56:45 Searching in path 'Z:\\u30db\u30c8\u30fb\u30a8\u30c3\u30c1\u30f3\u30b0\\u88fd\u54c1\\uff84\uff9e\uff97\uff72\uff74\uff6f\uff813\u53f7\u6a5f\3\uff72\uff9d\uff81' with pattern '*3\uff72\uff9d\uff81*BJ\uff8f\uff7d\uff78\u5f62\u6210*SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84*.xlsm'
2025-09-23 10:56:45,745 - INFO - 2025-09-23 10:56:45 Found latest source file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 10:56:47,782 - INFO - 2025-09-23 10:56:47 File copied successfully -> ..\DataFile\005_BJ1\3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 10:56:47,783 - INFO - 2025-09-23 10:56:47 --- Start processing file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm ---
2025-09-23 10:56:47,798 - ERROR - 2025-09-23 10:56:47 Error processing file 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm: Traceback (most recent call last):
  File "c:\Users\hsi67063\Documents\Kaizen-TDS\024_ISO-EML\ISO-EML-Special V0.3.py", line 415, in main
    process_excel_file(dst_path, settings, log_file, csv_filepath_for_this_ini)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\hsi67063\Documents\Kaizen-TDS\024_ISO-EML\ISO-EML-Special V0.3.py", line 189, in process_excel_file
    start_row = max(Row_Number_Func.start_row_number(settings.running_rec) - settings.skip_rows, 4)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\024_ISO-EML\../MyModule\Row_Number_Func.py", line 4, in start_row_number
    textfile = open(path,"r",encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: './BJ1_Dry3_StartRow.txt'

2025-09-23 10:56:47,800 - INFO - 2025-09-23 10:56:47 --- Finished processing config file: HL13_01.ini ---
2025-09-23 10:56:47,801 - INFO - 2025-09-23 10:56:47 ===== Universal Script End =====
2025-09-23 10:58:14,552 - INFO - 2025-09-23 10:58:14 --- Start processing config file: HL13_01.ini ---
2025-09-23 10:58:14,556 - INFO - 2025-09-23 10:58:14 CSV output for this config will be: C:\Users\hsi67063\Box\00-home-pigo.hsiao\TEMP\XML\BJ1_CVD_EtchingRate_Dry3_2025_09_23T10.58.14.csv
2025-09-23 10:58:14,557 - INFO - 2025-09-23 10:58:14 Searching in path 'Z:\\u30db\u30c8\u30fb\u30a8\u30c3\u30c1\u30f3\u30b0\\u88fd\u54c1\\uff84\uff9e\uff97\uff72\uff74\uff6f\uff813\u53f7\u6a5f\3\uff72\uff9d\uff81' with pattern '*3\uff72\uff9d\uff81*BJ\uff8f\uff7d\uff78\u5f62\u6210*SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84*.xlsm'
2025-09-23 10:58:14,736 - INFO - 2025-09-23 10:58:14 Found latest source file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 10:58:16,661 - INFO - 2025-09-23 10:58:16 File copied successfully -> ..\DataFile\005_BJ1\3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 10:58:16,663 - INFO - 2025-09-23 10:58:16 --- Start processing file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm ---
2025-09-23 10:58:21,892 - INFO - 2025-09-23 10:58:21 Step 1: Successfully read main sheet '\u30c7\u30fc\u30bf', 11825 rows loaded.
2025-09-23 10:58:21,893 - INFO - 2025-09-23 10:58:21 Pivoting logic detected. Starting data transformation...
2025-09-23 10:58:21,894 - ERROR - 2025-09-23 10:58:21 Step 1/2/3 failed: Error during Excel read or filter. Error: [None]
2025-09-23 10:58:21,896 - INFO - 2025-09-23 10:58:21 --- Finished processing config file: HL13_01.ini ---
2025-09-23 10:58:21,896 - INFO - 2025-09-23 10:58:21 ===== Universal Script End =====
2025-09-23 10:58:55,292 - INFO - 2025-09-23 10:58:55 --- Start processing config file: HL13_01.ini ---
2025-09-23 10:58:55,297 - INFO - 2025-09-23 10:58:55 CSV output for this config will be: C:\Users\hsi67063\Box\00-home-pigo.hsiao\TEMP\XML\BJ1_CVD_EtchingRate_Dry3_2025_09_23T10.58.55.csv
2025-09-23 10:58:55,300 - INFO - 2025-09-23 10:58:55 Searching in path 'Z:\\u30db\u30c8\u30fb\u30a8\u30c3\u30c1\u30f3\u30b0\\u88fd\u54c1\\uff84\uff9e\uff97\uff72\uff74\uff6f\uff813\u53f7\u6a5f\3\uff72\uff9d\uff81' with pattern '*3\uff72\uff9d\uff81*BJ\uff8f\uff7d\uff78\u5f62\u6210*SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84*.xlsm'
2025-09-23 10:58:55,479 - INFO - 2025-09-23 10:58:55 Found latest source file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 10:58:57,238 - INFO - 2025-09-23 10:58:57 File copied successfully -> ..\DataFile\005_BJ1\3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 10:58:57,238 - INFO - 2025-09-23 10:58:57 --- Start processing file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm ---
2025-09-23 10:59:01,786 - INFO - 2025-09-23 10:59:01 Step 1: Successfully read main sheet '\u30c7\u30fc\u30bf', 11825 rows loaded.
2025-09-23 10:59:01,786 - INFO - 2025-09-23 10:59:01 Pivoting logic detected. Starting data transformation...
2025-09-23 10:59:01,787 - ERROR - 2025-09-23 10:59:01 Step 1/2/3 failed: Error during Excel read or filter. Error: [None]
2025-09-23 10:59:01,789 - INFO - 2025-09-23 10:59:01 --- Finished processing config file: HL13_01.ini ---
2025-09-23 10:59:01,790 - INFO - 2025-09-23 10:59:01 ===== Universal Script End =====
2025-09-23 11:09:27,770 - INFO - 2025-09-23 11:09:27 --- Start processing config file: HL13_01.ini ---
2025-09-23 11:09:27,774 - INFO - 2025-09-23 11:09:27 CSV output for this config will be: C:\Users\hsi67063\Box\00-home-pigo.hsiao\TEMP\XML\BJ1_CVD_EtchingRate_Dry3_2025_09_23T11.09.27.csv
2025-09-23 11:09:27,776 - INFO - 2025-09-23 11:09:27 Searching in path 'Z:\\u30db\u30c8\u30fb\u30a8\u30c3\u30c1\u30f3\u30b0\\u88fd\u54c1\\uff84\uff9e\uff97\uff72\uff74\uff6f\uff813\u53f7\u6a5f\3\uff72\uff9d\uff81' with pattern '*3\uff72\uff9d\uff81*BJ\uff8f\uff7d\uff78\u5f62\u6210*SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84*.xlsm'
2025-09-23 11:09:27,960 - INFO - 2025-09-23 11:09:27 Found latest source file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 11:09:29,716 - INFO - 2025-09-23 11:09:29 File copied successfully -> ..\DataFile\005_BJ1\3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 11:09:29,717 - INFO - 2025-09-23 11:09:29 --- Start processing file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm ---
2025-09-23 11:09:29,726 - ERROR - 2025-09-23 11:09:29 Error processing file 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm: Traceback (most recent call last):
  File "c:\Users\hsi67063\Documents\Kaizen-TDS\024_ISO-EML\ISO-EML-Special V0.3.py", line 426, in main
    process_excel_file(dst_path, settings, log_file, csv_filepath_for_this_ini)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\hsi67063\Documents\Kaizen-TDS\024_ISO-EML\ISO-EML-Special V0.3.py", line 189, in process_excel_file
    start_row = max(Row_Number_Func.start_row_number(settings.running_rec) - settings.skip_rows, 4)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\024_ISO-EML\../MyModule\Row_Number_Func.py", line 4, in start_row_number
    textfile = open(path,"r",encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: './HL13_StartRow..txt'

2025-09-23 11:09:29,727 - INFO - 2025-09-23 11:09:29 --- Finished processing config file: HL13_01.ini ---
2025-09-23 11:09:29,727 - INFO - 2025-09-23 11:09:29 ===== Universal Script End =====
2025-09-23 11:13:14,747 - INFO - 2025-09-23 11:13:14 --- Start processing config file: HL13_01.ini ---
2025-09-23 11:13:14,750 - INFO - 2025-09-23 11:13:14 CSV output for this config will be: C:\Users\hsi67063\Box\00-home-pigo.hsiao\TEMP\XML\BJ1_CVD_EtchingRate_Dry3_2025_09_23T11.13.14.csv
2025-09-23 11:13:14,752 - INFO - 2025-09-23 11:13:14 Searching in path 'Z:\\u30db\u30c8\u30fb\u30a8\u30c3\u30c1\u30f3\u30b0\\u88fd\u54c1\\uff84\uff9e\uff97\uff72\uff74\uff6f\uff813\u53f7\u6a5f\3\uff72\uff9d\uff81' with pattern '*3\uff72\uff9d\uff81*BJ\uff8f\uff7d\uff78\u5f62\u6210*SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84*.xlsm'
2025-09-23 11:13:14,935 - INFO - 2025-09-23 11:13:14 Found latest source file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 11:13:16,539 - INFO - 2025-09-23 11:13:16 File copied successfully -> ..\DataFile\005_BJ1\3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 11:13:16,539 - INFO - 2025-09-23 11:13:16 --- Start processing file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm ---
2025-09-23 11:13:16,547 - ERROR - 2025-09-23 11:13:16 Error processing file 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm: Traceback (most recent call last):
  File "c:\Users\hsi67063\Documents\Kaizen-TDS\024_ISO-EML\ISO-EML-Special V0.3.py", line 428, in main
    process_excel_file(dst_path, settings, log_file, csv_filepath_for_this_ini)
    ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\hsi67063\Documents\Kaizen-TDS\024_ISO-EML\ISO-EML-Special V0.3.py", line 190, in process_excel_file
    start_row = max(Row_Number_Func.start_row_number(settings.running_rec) - settings.skip_rows, 4)
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\024_ISO-EML\../MyModule\Row_Number_Func.py", line 4, in start_row_number
    textfile = open(path,"r",encoding="utf-8")
FileNotFoundError: [Errno 2] No such file or directory: './HL13_StartRow.txt'

2025-09-23 11:13:16,549 - INFO - 2025-09-23 11:13:16 --- Finished processing config file: HL13_01.ini ---
2025-09-23 11:13:16,550 - INFO - 2025-09-23 11:13:16 ===== Universal Script End =====
2025-09-23 11:14:43,844 - INFO - 2025-09-23 11:14:43 --- Start processing config file: HL13_01.ini ---
2025-09-23 11:14:43,846 - INFO - 2025-09-23 11:14:43 CSV output for this config will be: C:\Users\hsi67063\Box\00-home-pigo.hsiao\TEMP\XML\BJ1_CVD_EtchingRate_Dry3_2025_09_23T11.14.43.csv
2025-09-23 11:14:43,848 - INFO - 2025-09-23 11:14:43 Searching in path 'Z:\\u30db\u30c8\u30fb\u30a8\u30c3\u30c1\u30f3\u30b0\\u88fd\u54c1\\uff84\uff9e\uff97\uff72\uff74\uff6f\uff813\u53f7\u6a5f\3\uff72\uff9d\uff81' with pattern '*3\uff72\uff9d\uff81*BJ\uff8f\uff7d\uff78\u5f62\u6210*SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84*.xlsm'
2025-09-23 11:14:44,024 - INFO - 2025-09-23 11:14:44 Found latest source file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 11:14:46,631 - INFO - 2025-09-23 11:14:46 File copied successfully -> ..\DataFile\005_BJ1\3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 11:14:46,631 - INFO - 2025-09-23 11:14:46 --- Start processing file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm ---
2025-09-23 11:14:46,633 - INFO - 2025-09-23 11:14:46 Attempting to read sheet '\u30c7\u30fc\u30bf' from row 20...
2025-09-23 11:14:51,302 - ERROR - 2025-09-23 11:14:51 Step 1/2/3 failed: Error during Excel read or filter. Error: Defining usecols with out-of-bounds indices is not allowed. [37, 38] are out-of-bounds. (sheet: \u30c7\u30fc\u30bf)
2025-09-23 11:14:51,346 - ERROR - 2025-09-23 11:14:51 Full traceback: Traceback (most recent call last):
  File "c:\Users\hsi67063\Documents\Kaizen-TDS\024_ISO-EML\ISO-EML-Special V0.3.py", line 196, in process_excel_file
    df_raw = pd.read_excel(filepath, header=None, sheet_name=settings.sheet_name, usecols=settings.data_columns, skiprows=start_row)
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 508, in read_excel
    data = io.parse(
        sheet_name=sheet_name,
    ...<21 lines>...
        dtype_backend=dtype_backend,
    )
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 1616, in parse
    return self._reader.parse(
           ~~~~~~~~~~~~~~~~~~^
        sheet_name=sheet_name,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<17 lines>...
        **kwds,
        ^^^^^^^
    )
    ^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 916, in parse
    raise err
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 878, in parse
    parser = TextParser(
        data,
    ...<20 lines>...
        **kwds,
    )
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 2053, in TextParser
    return TextFileReader(*args, **kwds)
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\python_parser.py", line 133, in __init__
    ) = self._infer_columns()
        ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\python_parser.py", line 551, in _infer_columns
    columns = self._handle_usecols(columns, columns[0], ncols)
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\python_parser.py", line 617, in _handle_usecols
    raise ParserError(
    ...<2 lines>...
    )
pandas.errors.ParserError: Defining usecols with out-of-bounds indices is not allowed. [37, 38] are out-of-bounds. (sheet: \u30c7\u30fc\u30bf)

2025-09-23 11:14:51,347 - INFO - 2025-09-23 11:14:51 --- Finished processing config file: HL13_01.ini ---
2025-09-23 11:14:51,347 - INFO - 2025-09-23 11:14:51 ===== Universal Script End =====
2025-09-23 11:16:35,283 - INFO - 2025-09-23 11:16:35 --- Start processing config file: HL13_01.ini ---
2025-09-23 11:16:35,286 - INFO - 2025-09-23 11:16:35 CSV output for this config will be: C:\Users\hsi67063\Box\00-home-pigo.hsiao\TEMP\XML\BJ1_CVD_EtchingRate_Dry3_2025_09_23T11.16.35.csv
2025-09-23 11:16:35,287 - INFO - 2025-09-23 11:16:35 Searching in path 'Z:\\u30db\u30c8\u30fb\u30a8\u30c3\u30c1\u30f3\u30b0\\u88fd\u54c1\\uff84\uff9e\uff97\uff72\uff74\uff6f\uff813\u53f7\u6a5f\3\uff72\uff9d\uff81' with pattern '*3\uff72\uff9d\uff81*BJ\uff8f\uff7d\uff78\u5f62\u6210*SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84*.xlsm'
2025-09-23 11:16:35,468 - INFO - 2025-09-23 11:16:35 Found latest source file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 11:16:38,099 - INFO - 2025-09-23 11:16:38 File copied successfully -> ..\DataFile\005_BJ1\3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 11:16:38,099 - INFO - 2025-09-23 11:16:38 --- Start processing file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm ---
2025-09-23 11:16:38,101 - INFO - 2025-09-23 11:16:38 Attempting to read sheet '\u30c7\u30fc\u30bf' from row 20...
2025-09-23 11:16:42,770 - ERROR - 2025-09-23 11:16:42 Step 1/2/3 failed: Error during Excel read or filter. Error: Defining usecols with out-of-bounds indices is not allowed. [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51] are out-of-bounds. (sheet: \u30c7\u30fc\u30bf)
2025-09-23 11:16:42,787 - ERROR - 2025-09-23 11:16:42 Full traceback: Traceback (most recent call last):
  File "c:\Users\hsi67063\Documents\Kaizen-TDS\024_ISO-EML\ISO-EML-Special V0.3.py", line 196, in process_excel_file
    df_raw = pd.read_excel(filepath, header=None, sheet_name=settings.sheet_name, usecols=settings.data_columns, skiprows=start_row)
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 508, in read_excel
    data = io.parse(
        sheet_name=sheet_name,
    ...<21 lines>...
        dtype_backend=dtype_backend,
    )
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 1616, in parse
    return self._reader.parse(
           ~~~~~~~~~~~~~~~~~~^
        sheet_name=sheet_name,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<17 lines>...
        **kwds,
        ^^^^^^^
    )
    ^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 916, in parse
    raise err
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 878, in parse
    parser = TextParser(
        data,
    ...<20 lines>...
        **kwds,
    )
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 2053, in TextParser
    return TextFileReader(*args, **kwds)
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\python_parser.py", line 133, in __init__
    ) = self._infer_columns()
        ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\python_parser.py", line 551, in _infer_columns
    columns = self._handle_usecols(columns, columns[0], ncols)
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\python_parser.py", line 617, in _handle_usecols
    raise ParserError(
    ...<2 lines>...
    )
pandas.errors.ParserError: Defining usecols with out-of-bounds indices is not allowed. [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51] are out-of-bounds. (sheet: \u30c7\u30fc\u30bf)

2025-09-23 11:16:42,788 - INFO - 2025-09-23 11:16:42 --- Finished processing config file: HL13_01.ini ---
2025-09-23 11:16:42,788 - INFO - 2025-09-23 11:16:42 ===== Universal Script End =====
2025-09-23 11:21:20,840 - INFO - 2025-09-23 11:21:20 --- Start processing config file: HL13_01.ini ---
2025-09-23 11:21:20,842 - INFO - 2025-09-23 11:21:20 CSV output for this config will be: C:\Users\hsi67063\Box\00-home-pigo.hsiao\TEMP\XML\BJ1_CVD_EtchingRate_Dry3_2025_09_23T11.21.20.csv
2025-09-23 11:21:20,844 - INFO - 2025-09-23 11:21:20 Searching in path 'Z:\\u30db\u30c8\u30fb\u30a8\u30c3\u30c1\u30f3\u30b0\\u88fd\u54c1\\uff84\uff9e\uff97\uff72\uff74\uff6f\uff813\u53f7\u6a5f\3\uff72\uff9d\uff81' with pattern '*3\uff72\uff9d\uff81*BJ\uff8f\uff7d\uff78\u5f62\u6210*SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84*.xlsm'
2025-09-23 11:21:21,032 - INFO - 2025-09-23 11:21:21 Found latest source file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 11:21:23,663 - INFO - 2025-09-23 11:21:23 File copied successfully -> ..\DataFile\005_BJ1\3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm
2025-09-23 11:21:23,664 - INFO - 2025-09-23 11:21:23 --- Start processing file: 3\uff72\uff9d\uff81 BJ\uff8f\uff7d\uff78\u5f62\u6210 SiO2\u819c\uff84\uff9e\uff97\uff72\uff74\uff6f\uff81 \uff8c\uff9f\uff9b\uff78\uff9e\uff97\uff91\uff7c\uff70\uff84.xlsm ---
2025-09-23 11:21:23,668 - INFO - 2025-09-23 11:21:23 Attempting to read sheet '\u30c7\u30fc\u30bf' from row 20...
2025-09-23 11:21:28,406 - ERROR - 2025-09-23 11:21:28 Step 1/2/3 failed: Error during Excel read or filter. Error: Defining usecols with out-of-bounds indices is not allowed. [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51] are out-of-bounds. (sheet: \u30c7\u30fc\u30bf)
2025-09-23 11:21:28,429 - ERROR - 2025-09-23 11:21:28 Full traceback: Traceback (most recent call last):
  File "c:\Users\hsi67063\Documents\Kaizen-TDS\024_ISO-EML\ISO-EML-Special V0.3.py", line 196, in process_excel_file
    df_raw = pd.read_excel(filepath, header=None, sheet_name=settings.sheet_name, usecols=settings.data_columns, skiprows=start_row)
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 508, in read_excel
    data = io.parse(
        sheet_name=sheet_name,
    ...<21 lines>...
        dtype_backend=dtype_backend,
    )
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 1616, in parse
    return self._reader.parse(
           ~~~~~~~~~~~~~~~~~~^
        sheet_name=sheet_name,
        ^^^^^^^^^^^^^^^^^^^^^^
    ...<17 lines>...
        **kwds,
        ^^^^^^^
    )
    ^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 916, in parse
    raise err
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\excel\_base.py", line 878, in parse
    parser = TextParser(
        data,
    ...<20 lines>...
        **kwds,
    )
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 2053, in TextParser
    return TextFileReader(*args, **kwds)
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1620, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\readers.py", line 1898, in _make_engine
    return mapping[engine](f, **self.options)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\python_parser.py", line 133, in __init__
    ) = self._infer_columns()
        ~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\python_parser.py", line 551, in _infer_columns
    columns = self._handle_usecols(columns, columns[0], ncols)
  File "C:\Users\hsi67063\Documents\Kaizen-TDS\.venv\Lib\site-packages\pandas\io\parsers\python_parser.py", line 617, in _handle_usecols
    raise ParserError(
    ...<2 lines>...
    )
pandas.errors.ParserError: Defining usecols with out-of-bounds indices is not allowed. [37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51] are out-of-bounds. (sheet: \u30c7\u30fc\u30bf)

2025-09-23 11:21:28,433 - INFO - 2025-09-23 11:21:28 --- Finished processing config file: HL13_01.ini ---
2025-09-23 11:21:28,440 - INFO - 2025-09-23 11:21:28 ===== Universal Script End =====
